livraria/livraria/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('livros/', include(('livros.urls', 'livros'), namespace='livros')),
    path('', views.home, name='home'),
    path('sobre/', views.about, name='about'),
    path('book/', views.book, name='cadastro'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livraria/livros/urls.py
from django.urls import path
from . import views

app_name = 'livros'

urlpatterns = [
    
    path('home/', views.home, name='home'),
    path('comprar/', views.comprar, name='comprar'),
    path('alugar/', views.alugar, name='alugar'),
    path('livro/<int:id>/', views.detalhes_livro, name='detalhes_livro'),
    path('carrinho/', views.ver_carrinho, name='ver_carrinho'),
    path('carrinho/adicionar/<int:livro_id>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('carrinho/remover/<int:livro_id>/', views.remover_do_carrinho, name='remover_do_carrinho'),
    path('carrinho/finalizar/', views.finalizar_compra, name='finalizar_compra'),

]

livraria/livros/models.py
from django.db import models

class Genero(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Livro(models.Model):
    titulo = models.CharField(max_length=200)
    autor = models.CharField(max_length=150)
    descricao = models.TextField(blank=True)
    genero = models.ForeignKey(Genero, on_delete=models.SET_NULL, null=True)
    capa = models.ImageField(upload_to='capas/', blank=True, null=True)
    preco_venda = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    preco_aluguel = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    disponivel_para_venda = models.BooleanField(default=True)
    disponivel_para_aluguel = models.BooleanField(default=True)
    estoque = models.PositiveIntegerField(default=0)  # Quantidade disponível

    def __str__(self):
        return self.titulo

livraria/livraria/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def menu(request):
    return render(request, 'comprar.html')

def alugar(request):
    return render(request, 'alugar.html')

def about(request):
    return render(request, 'about.html')

def book(request):
    return render(request, 'book.html')

livraria/livros/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Livro, Genero
from django.contrib import messages

def home(request):
    livros_venda = Livro.objects.filter(preco_venda__isnull=False)
    livros_aluguel = Livro.objects.filter(preco_aluguel__isnull=False)
    generos = Genero.objects.all()
    return render(request, 'home.html', {
        'livros_venda': livros_venda,
        'livros_aluguel': livros_aluguel,
        'generos': generos
    })


def comprar(request):
    genero_id = request.GET.get('genero')
    livros = Livro.objects.filter(disponivel_para_venda=True)
    if genero_id:
        livros = livros.filter(genero_id=genero_id)

    generos = Genero.objects.all()
    return render(request, 'comprar.html', {
        'livros': livros,
        'generos': generos
    })

def alugar(request):
    genero_id = request.GET.get('genero')
    livros = Livro.objects.filter(disponivel_para_aluguel=True)
    if genero_id:
        livros = livros.filter(genero_id=genero_id)

    generos = Genero.objects.all()
    return render(request, 'alugar.html', {
        'livros': livros,
        'generos': generos
    })

def detalhes_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    return render(request, 'detalhes_livro.html', {
        'livro': livro
    })



def adicionar_ao_carrinho(request, livro_id):
    carrinho = request.session.get('carrinho', [])
    if livro_id not in carrinho:
        carrinho.append(livro_id)
        request.session['carrinho'] = carrinho
    return redirect('livros:ver_carrinho')

def remover_do_carrinho(request, livro_id):
    carrinho = request.session.get('carrinho', [])
    if livro_id in carrinho:
        carrinho.remove(livro_id)
        request.session['carrinho'] = carrinho
    return redirect('livros:ver_carrinho')

def ver_carrinho(request):
    carrinho = request.session.get('carrinho', [])
    livros = Livro.objects.filter(id__in=carrinho)
    total = sum(livro.preco_venda for livro in livros)
    return render(request, 'carrinho.html', {
        'livros': livros,
        'total': total
    })

def finalizar_compra(request):
    if request.method == 'POST':
        request.session['carrinho'] = []
        messages.success(request, "Compra finalizada com sucesso!")
        return redirect('livros:comprar')

livraria/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sobre Nós - Estação Literária{% endblock %}

{% block content %}
<section class="about_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="img-box">
          <img src="{% static 'images/about-img.png' %}" alt="">
        </div>
      </div>
      <div class="col-md-6">
        <div class="detail-box">
          <div class="heading_container">
            <h2>Sobre nossa Livraria</h2>
          </div>
          <p>
            Essa Livraria online foi criada com a proposta de oferecer venda e aluguel de Livros.
            Inspirado nas antigas livrarias e estações de trem, o site busca trazer uma experiência aconchegante,
            nostálgica e funcional.
          </p>
          <a href="#">Read More</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

livraria/templates/alugar.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Alugar - Estação Literária{% endblock %}

{% block content %}


  <!-- food section -->

  <section class="food_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Para Alugar
        </h2>
      </div>

<ul class="filters_menu">
          <li class="active" data-filter="*">Todos</li>
          {% for genero in generos %}
            <li data-filter=".{{ genero.nome|slugify }}">{{ genero.nome }}</li>
          {% endfor %}
        </ul>

      <div class="filters-content">
        <div class="row grid"> 
          {% for livro in livros %}
          <div class="col-sm-6 col-lg-4 all {{ livro.genero.nome|slugify }}">
            
            <div class="box">
              <div>
                
                <div class="img-box">
                    {% if livro.capa %}
                      <img src="{{ livro.capa.url }}" alt="Capa de {{ livro.titulo }}" style="max-height: 200px; width: auto;">
                    {% else %}
                      <img src="{% static 'images/capa-padrao.jpg' %}" alt="Capa padrão" style="max-height: 200px; width: auto;">
                    {% endif %}
                </div>

                <div class="detail-box {{ livro.genero.nome|slugify }}">      
                  
                  <h5>{{ livro.titulo }}</h5>
                  <p>{{ livro.descricao|truncatewords:20 }}</p>
                  <div class="options">
                    <h6>${{ livro.preco_venda }}</h6>
                    <a href="{% url 'livros:detalhes_livro' livro.id %}">
                      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                        <g>
                          <g>
                            <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                         c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                         C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                         c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                         C457.728,97.71,450.56,86.958,439.296,84.91z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                         c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                          </g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                      </svg>
                    </a>
                  </div>
                </div>
                
                
              </div>
            </div>
              
          </div>
          {% empty %}
                  <p>Nenhum livro disponível.</p>
          {% endfor %}
        </div>
          <div class="col-sm-6 col-lg-4 all pasta">
      <div class="btn-box">
        <a href="">
          View More
        </a>
      </div>
      
    </div>
  </section>

  <!-- end food section -->

  {% endblock %}

livraria/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{% block title %}Estação Literária{% endblock %}</title>

  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>

<body class="sub_page">
  <div class="hero_area">
    <div class="bg-box">
      <img src="{% static 'images/hero-bg.jpg' %}" alt="">
    </div>

    {% include 'includes/navbar.html' %}
  </div>

  {% block content %}{% endblock %}

  {% include 'includes/footer.html' %}

</body>

</html>

livraria/templates/book.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Seja membro - Estação Literária{% endblock %}

{% block content %}

  <!-- book section -->
  <section class="book_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Book A Table
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <form action="">
              <div>
                <input type="text" class="form-control" placeholder="Your Name" />
              </div>
              <div>
                <input type="text" class="form-control" placeholder="Phone Number" />
              </div>
              <div>
                <input type="email" class="form-control" placeholder="Your Email" />
              </div>
              <div>
                <select class="form-control nice-select wide">
                  <option value="" disabled selected>
                    How many persons?
                  </option>
                  <option value="">
                    2
                  </option>
                  <option value="">
                    3
                  </option>
                  <option value="">
                    4
                  </option>
                  <option value="">
                    5
                  </option>
                </select>
              </div>
              <div>
                <input type="date" class="form-control">
              </div>
              <div class="btn_box">
                <button>
                  Book Now
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-6">
          <div class="map_container ">
            <div id="googleMap"></div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end book section -->
 {% endblock %}

livraria/templates/carrinho.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Carrinho - Estação Literária{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Seu Carrinho</h2>

    {% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    {% if livros %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Capa</th>
                    <th>Título</th>
                    <th>Autor</th>
                    <th>Preço</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for livro in livros %}
                <tr>
                    <td>
                        {% if livro.capa %}
                            <img src="{{ livro.capa.url }}" alt="{{ livro.titulo }}" width="60">
                        {% else %}
                            <span>Sem capa</span>
                        {% endif %}
                    </td>
                    <td>{{ livro.titulo }}</td>
                    <td>{{ livro.autor }}</td>
                    <td>
                        {% if livro.preco_venda %}
                            R$ {{ livro.preco_venda }}
                        {% elif livro.preco_aluguel %}
                            R$ {{ livro.preco_aluguel }} (aluguel)
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn btn-danger btn-sm" href="{% url 'livros:remover_do_carrinho' livro.id %}">Remover</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="mt-3">
            <h4>Total: <strong>R$ {{ total }}</strong></h4>

            <form method="post" action="{% url 'livros:finalizar_compra' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Finalizar Compra</button>
            </form>
        </div>

        <a class="btn btn-primary mt-3" href="{% url 'livros:comprar' %}">Voltar às compras</a>
    {% else %}
        <p>Seu carrinho está vazio.</p>
        <a class="btn btn-primary" href="{% url 'livros:comprar' %}">Comprar livros</a>
        <a class="btn btn-secondary" href="{% url 'livros:alugar' %}">Alugar livros</a>
    {% endif %}
</div>
{% endblock %}

livraria/templates/comprar.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Comprar - Estação Literária{% endblock %}

{% block content %}

  <!-- food section -->

  <section class="food_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          A venda
        </h2>
      </div>

        <ul class="filters_menu">
          <li class="active" data-filter="*">Todos</li>
          {% for genero in generos %}
            <li data-filter=".{{ genero.nome|slugify }}">{{ genero.nome }}</li>
          {% endfor %}
        </ul>

      <div class="filters-content">
        <div class="row grid"> 
          {% for livro in livros %}
          <div class="col-sm-6 col-lg-4 all {{ livro.genero.nome|slugify }}">
            
            <div class="box">
              <div>
                
                <div class="img-box">
                    {% if livro.capa %}
                      <img src="{{ livro.capa.url }}" alt="Capa de {{ livro.titulo }}" style="max-height: 200px; width: auto;">
                    {% else %}
                      <img src="{% static 'images/capa-padrao.jpg' %}" alt="Capa padrão" style="max-height: 200px; width: auto;">
                    {% endif %}
                </div>

                <div class="detail-box {{ livro.genero.nome|slugify }}">      
                  
                  <h5>{{ livro.titulo }}</h5>
                  <p>{{ livro.descricao|truncatewords:20 }}</p>
                  <div class="options">
                    <h6>${{ livro.preco_venda }}</h6>
                    <a href="{% url 'livros:detalhes_livro' livro.id %}">
                      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                        <g>
                          <g>
                            <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                         c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                         C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                         c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                         C457.728,97.71,450.56,86.958,439.296,84.91z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                         c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                          </g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                      </svg>
                    </a>
                  </div>
                </div>
                
                
              </div>
            </div>
              
          </div>
          {% empty %}
                  <p>Nenhum livro disponível.</p>
          {% endfor %}
        </div>
          <div class="col-sm-6 col-lg-4 all pasta">
      <div class="btn-box">
        <a href="">
          View More
        </a>
      </div>
    </div>
  </section>


  {% endblock %}

livraria/templates/detalhes_livro.html
{% extends 'base.html' %}
{% load static %}

{% block title %} detalhes_livro - Estação Literária{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-4">
      {% if livro.capa %}
        <img src="{{ livro.capa.url }}" class="img-fluid" alt="Capa do livro">
      {% else %}
        <img src="{% static 'default-cover.jpg' %}" class="img-fluid" alt="Sem capa">
      {% endif %}
    </div>
    <div class="col-md-8">
      <h2>{{ livro.titulo }}</h2>
      <p><strong>Autor:</strong> {{ livro.autor }}</p>
      <p><strong>Gênero:</strong> {{ livro.genero.nome }}</p>
      <p><strong>Descrição:</strong> {{ livro.descricao }}</p>
      <p><strong>Preço de venda:</strong> R$ {{ livro.preco_venda }}</p>
      <p><strong>Preço de aluguel:</strong> R$ {{ livro.preco_aluguel }}</p>

      {% if livro.id in request.session.carrinho %}
        <p class="text-success">Este livro já está no carrinho.</p>
      {% else %}
        <a href="{% url 'livros:adicionar_ao_carrinho' livro.id %}" class="btn btn-primary">
          Adicionar ao carrinho
        </a>
      {% endif %}

      <br><br>
      <a href="{% url 'livros:comprar' %}" class="btn btn-secondary">Voltar</a>
    </div>
  </div>
</div>
{% endblock %}

livraria/templates/includes/footer.html
{% load static %}
<footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>Entre em contato</h4>
            <div class="contact_link_box">
              <a href="#"><i class="fa fa-map-marker"></i><span>Loclização</span></a>
              <a href="#"><i class="fa fa-phone"></i><span>Ligue +55 (65) 99226-2626</span></a>
              <a href="#"><i class="fa fa-envelope"></i><span>estacaoLiteraria@gmail.com</span></a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="#" class="footer-logo">Estação Literária</a>
            <p>Além de nossa biblioteca virtual, conheça nossa livraria Fisica</p>
            <div class="footer_social">
              <a href="#"><i class="fa fa-facebook"></i></a>
              <a href="#"><i class="fa fa-twitter"></i></a>
              <a href="#"><i class="fa fa-linkedin"></i></a>
              <a href="#"><i class="fa fa-instagram"></i></a>
              <a href="#"><i class="fa fa-pinterest"></i></a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>Aberto 24 horas</h4>
          <!-- Coloque o conteúdo desejado aqui -->
        </div>
      </div>
    </div>
  </footer>
  

livraria/templates/includes/navbar.html
{% load static %}
<header class="header_section">
    <div class="container">
      <nav class="navbar navbar-expand-lg custom_nav-container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <span>Estação Literária</span>
        </a>
  
        <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto">
        <li class="nav-item"><a class="nav-link" href="{% url 'livros:comprar' %}">Comprar</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'livros:alugar' %}">Alugar</a></li>
          </ul>
          <div class="user_option">
            <a href="#" class="user_link"><i class="fa fa-user" aria-hidden="true"></i></a>
            <a class="cart_link" href="{% url 'livros:ver_carrinho' %}"><i class="fa fa-shopping-cart"></i></a>
            <form class="form-inline">
              <button class="btn my-2 my-sm-0 nav_search-btn" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </form>
            <a href="#" class="order_online">Order Online</a>
          </div>
        </div>
      </nav>
    </div>
  </header>
  

templates/comprar.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Comprar - Estação Literária{% endblock %}

{% block content %}

  <!-- food section -->

  <section class="food_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          A venda
        </h2>
      </div>

        <ul class="filters_menu">
          <li class="active" data-filter="*">Todos</li>
          {% for genero in generos %}
            <li data-filter=".{{ genero.nome|slugify }}">{{ genero.nome }}</li>
          {% endfor %}
        </ul>

      <div class="filters-content">
        <div class="row grid"> 
          {% for livro in livros %}
          <div class="col-sm-6 col-lg-4 all {{ livro.genero.nome|slugify }}">
            
            <div class="box">
              <div>
                
                <div class="img-box">
                    {% if livro.capa %}
                      <img src="{{ livro.capa.url }}" alt="Capa de {{ livro.titulo }}" style="max-height: 200px; width: auto;">
                    {% else %}
                      <img src="{% static 'images/capa-padrao.jpg' %}" alt="Capa padrão" style="max-height: 200px; width: auto;">
                    {% endif %}
                </div>

                <div class="detail-box {{ livro.genero.nome|slugify }}">      
                  
                  <h5>{{ livro.titulo }}</h5>
                  <p>{{ livro.descricao|truncatewords:20 }}</p>
                  <div class="options">
                    <h6>${{ livro.preco_venda }}</h6>
                    <a href="{% url 'livros:detalhes_livro' livro.id %}">
                      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                        <g>
                          <g>
                            <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                         c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                         C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                         c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                         C457.728,97.71,450.56,86.958,439.296,84.91z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                         c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                          </g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                      </svg>
                    </a>
                  </div>
                </div>
                
                
              </div>
            </div>
              
          </div>
          {% empty %}
                  <p>Nenhum livro disponível.</p>
          {% endfor %}
        </div>
          <div class="col-sm-6 col-lg-4 all pasta">
      <div class="btn-box">
        <a href="">
          View More
        </a>
      </div>
    </div>
  </section>

  <!-- end food section -->

  {% endblock %}